language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm test
  - codecov
after_success:
  - if [ "$TRAVIS_BRANCH" == "combined" ]; then
      npm run build && npm install -g travis-deploy-once @semantic-release/changelog @semantic-release/git semantic-release && npm run travis-deploy-once "npm run semantic-release"
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
