sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
script:
  - npm run lint
  - npm test
after_success:
  - if [ `node --version | cut -c 2-3` == '10' ] && [ "$TRAVIS_BRANCH" == "combined" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      npm install -g codecov;
      codecov;
      npm run build;
      npm install -g @semantic-release/changelog @semantic-release/git semantic-release travis-deploy-once;
      travis-deploy-once;
      semantic-release;
    fi
branches:
  except:
    - /^master|(?:v\d+\.\d+\.\d+)$/
