sudo: false
dist: trusty
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
script:
  - if [ `node --version | cut -c 2-3` == '10' ]; then
      BABEL_ENV=build node build;
    fi
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^master|(?:v\d+\.\d+\.\d+)$/
