language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
install:
  - npm install -g codecov travis-deploy-once @semantic-release/changelog @semantic-release/git semantic-release && npm install
script:
  - npm run lint
  - npm test
  - codecov
after_success:
  - test `node --version | cut -c 2-3` -eq 10 && npm run build && npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^master|(?:v\d+\.\d+\.\d+)$/
