sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
script:
  - npm run lint
  - npm test
  - test `node --version | cut -c 2-3` == '10' && ./node_modules/.bin/codecov
  - test `node --version | cut -c 2-3` == '10' && BABEL_ENV=build node build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^master|(?:v\d+\.\d+\.\d+)$/
