sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  #- '8'
  #- '6'
script:
  #- npm run lint
  #- npm test
  - if [ `node --version | cut -c 2-3` == '10' ]; then
      #./node_modules/.bin/codecov;
      BABEL_ENV=build node build;
    fi
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^master|(?:v\d+\.\d+\.\d+)$/
